CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saved_books (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    authors TEXT,
    thumbnail_url TEXT,
    comment TEXT,
    saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);